#!/bin/sh
if [ "$OLD_EMAIL" = "" ]
then
    echo "Set OLD_EMAIL env var"
    exit 1
fi

export CORRECT_NAME=${CORRECT_NAME:-"Eric Stern"}
export CORRECT_EMAIL=${CORRECT_EMAIL:-"eric@ericstern.com"}

git filter-branch --env-filter '
if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags
